language: python
python:
  - "2.7"

install: 
  - pip install suds
  - pip install flake8
  - pip install coveralls

before_script: flake8 .

script:
  - py.test coveralls/test/pycep_correios_test.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls
