language: python
python:
  - "2.7"
  - "3.4"

install: pip install -r requirements.txt

before_script: flake8 .

script:
  - coverage run --source=pycep_correios setup.py test

after_success:
  - coveralls
